name: transport_statarb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - yfinance
  - scikit-learn
  - statsmodels
  - scipy
  - jupyter
  - notebook
  - ipykernel